### ISSUE TITLE
The example in the README is misleading

### ISSUE THREAD

**Issue by alexwlchan** [mtgrosser/rszr#18]
If I run the example, in the README with rszr 1.2.1, the `image` variable doesn't actually change, because `resize` returns a new value rather than mutating the image in-place:

```ruby
image = Rszr::Image.load('image.jpg')
puts image.dimensions  # [2623, 3934]

image.resize(400, 300)
puts image.dimensions  # [2623, 3934]
```

I think the example should go:

```diff
 image = Rszr::Image.load('image.jpg')
-image.resize(400, 300)
+image = image.resize(400, 300)
```

but I'm not sure if the mistake is in the code or the example.

**Comment by mtgrosser** [comment]
Thank you for the hint, README was updated in 6130455093194226aa0e1440303521725f7440b7.
