### ISSUE TITLE
Greyscale?

### ISSUE THREAD

**Issue by dshorthouse** [mtgrosser/rszr#20]
I see some color handling here, though am stumped if you could use these to convert a color image to greyscale. Is that possible? How might you do that?

**Comment by mtgrosser** [comment]
In order to do this, you would have to manipulate pixel data directly, which would be inefficient in Ruby. I therefore added a little C impl in 8d184e9, released as v1.5.0.

**Comment by dshorthouse** [comment]
Tested and works great!
