### ISSUE TITLE
Rszr::SaveError: Unsupported format

### ISSUE THREAD

**Issue by jewe** [mtgrosser/rszr#7]
If i try to save an image as webp, i get this error:
Rszr::SaveError: Unsupported format

On my development system everything works, but on the production system the script fails, but JPG saving is possible.
Both are Ubuntu 5.4.0-65-generic

Any Ideas? Thanks!

**Comment by mtgrosser** [comment]
Probably the webp loader (/usr/lib/x86_64-linux-gnu/imlib2/loaders/webp.la) is missing from your imlib2 version. Newer Ubuntu versions seem to have it, older don't:

bionic: https://packages.ubuntu.com/bionic/amd64/libimlib2-dev/filelist

focal: https://packages.ubuntu.com/focal/amd64/libimlib2-dev/filelist

You could try to rebuild the package (or a more recent version of it) and make sure the webp loader is enabled.

**Comment by jewe** [comment]
Thank you! You are right: /usr/lib/x86_64-linux-gnu/imlib2/loaders/webp.la is missing.
I will try to rebuild the package.
